### PR TITLE
Replicated changes on other language sites

### PR DESCRIPTION
**Pull request by falquinho**
I've also fixed language changing on the german version.
I'm looking into a better way of handling internationalization.
This is too time consuming.

### CODE REVIEW

**Comment by Enovale** [comment]
I mean, you could turn the translation into JS, and/or make the index.html of each translation use the dependencies from root instead of its folder (main.js/payloads.js/style.css)

**Comment by falquinho** [comment]
Yeah, you're rigth.
I was just looking for a widely used proven framework. But it seems like everything
out there is overkill for this simple site.
I'll study a bit more and come up with somethin.

**Comment by Enovale** [comment]
Why don't you (or i) just set a `language` variable, and when you click a button it sets all the relevant elements' innerHTML to the translated versions accordingly?

**Comment by Enovale** [comment]
That way you can delete all the extra sub directories, and use the original dependencies, and everything updates properly.

**Comment by falquinho** [comment]
I'll think i'll do DOM manipulation + JSON to hold translation data.

**Comment by Enovale** [comment]
Good idea, for easy translation adding.

Ill just keep this pull req open for now.

**Comment by Enovale** [comment]
Nice! Good job. Merging...

**Comment by falquinho** [comment]
Hey i finished it :) 
Give it a check.
https://falquinho.github.io/web-cfw-loader/
https://github.com/falquinho/web-cfw-loader
I'll wait for your OK and then i'll make a pull request.

**Comment by falquinho** [comment]
Well that was fast!

**Pull request merged**
